### PR TITLE
feat: add themes for Kitty

### PR DESCRIPTION
**Pull request by kevhlee**
Hello!

I really like this colorscheme and I thought that it would be nice to have this available on [Kitty](https://sw.kovidgoyal.net/kitty/). Thus, I created all three versions of the Bamboo colorscheme for it. Let me know what you think and/or if I need to make any changes.

Here are some images for reference:

### Bamboo:

bamboo-kitty

### Bamboo Multiplex:

bamboo-multiplex-kitty

### Bamboo Light:

bamboo-light-kitty

### CODE REVIEW

**Comment by ribru17** [comment]
Thank you so much, this looks amazing! My only change request would be a small nitpick, which would be to replace the spaces in the file names with underscores, just in case the spaces cause issues for some users or OS's

**Comment by kevhlee** [comment]
Hi @ribru17, will do!

**Comment by kevhlee** [comment]
@ribru17, I changed the filenames to use underscore. Also, just to make them consistent with the rest of the terminal themes, I also made the filenames lowercase.

**Comment by ribru17** [comment]
Thanks so much, I appreciate it!

**Comment by kevhlee** [comment]
@ribru17, you're welcome! Happy to contribute 🙂.

**Pull request merged**
